project:
  type: website

website:
  title: "STARS"
  description: "Website for the STARS project"
  favicon: images/stars_logo_blue.png
  navbar:
    logo: images/stars_logo_white.png
    left:
      - pages/research.qmd
      - pages/publications.qmd
    tools:
      - icon: github
        menu:
          - text: View the STARS GitHub
            href: https://github.com/pythonhealthdatascience
          - text: View the code for this website
            href: https://github.com/pythonhealthdatascience/stars
  sidebar:
    - id: research
      style: "docked"
      title: "Research"
      contents:
        - pages/research.qmd
        - section: "Reproducible"
          contents:
            - pages/computational_reproducibility.qmd
            - pages/des_rap_book.qmd
            - pages/jos_mri.qmd
            - pages/hdr_uk_futures.qmd
        - section: "Reusable"
          contents:
            - pages/des_sharing_review.qmd
            - pages/stars_framework.qmd
            - pages/eom_rcc.qmd
        - section: "Replicable"
          contents:
            - pages/stress.qmd
        - pages/model_reviews.qmd
        - pages/llm_generate_des.qmd
        - pages/simtools.qmd
  page-footer:
    center: |
      ![](/images/exeter.png){width=150px}
      ![](/images/somerset.jpg){width=100px}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      ![](/images/ukmrc.png){width=150px}&nbsp;&nbsp;&nbsp;
      ![](/images/nihr.png){width=200px}

format:
  html:
    theme:
      - cosmo
      - css/theme.scss
    css:
      - css/footer.css
      - css/theme.css
    lightbox: true
    title-block-banner: images/banner.png
    title-block-banner-color: "#ffffff"