project:
  type: website

website:
  title: "STARS"
  description: "Website for the STARS project"
  favicon: images/stars_logo_blue.png
  navbar:
    logo: images/stars_logo_white.png
    left:
      - pages/reproducible.qmd
      - pages/reusable.qmd
      - pages/replicable.qmd
      - pages/llms.qmd
      - pages/simtools.qmd
    tools:
      - icon: github
        menu:
          - text: View the STARS GitHub
            href: https://github.com/pythonhealthdatascience
          - text: View the code for this website
            href: https://github.com/pythonhealthdatascience/stars

format:
  html:
    theme:
      - cosmo
      - css/theme.scss
    lightbox: true